### ISSUE TITLE
Message input doesn't clear

### ISSUE THREAD

**Issue by gavinmorrow** [Garmelon/cove#3]
When you send a message normally, the input box clears for when you want to write another message. 

However, when you click the down arrow right after sending the message, the input doesn't clear. 

https://user-images.githubusercontent.com/72874398/222168748-4cceae71-42b1-44c0-91b7-b443a248bd97.mp4

**Comment by Garmelon** [comment]
This is intentional. When the cursor disappears or is moved before the server has replied to the `send` event, cove keeps the editor contents. This is especially useful when you have a flaky connection. It is more frustrating to retype an entire message than to clear the editor with `Ctrl+L`.

In theory, I could use more complicated heuristics to detect whether a message was sent successfully, but I don't think it would be worth the added complexity.
